### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot write value of type class java.lang.Double

### ISSUE THREAD

**Issue by jcf** [clojure-emacs/cider-nrepl#251]
Having updated `cider-nrepl` today I'm no longer able to start a REPL because `clojure.tools.nrepl.bencode` can't encode doubles.

```
nREPL server started on port 49789 on host 127.0.0.1 - nrepl://127.0.0.1:49789
Exception in thread "nREPL-worker-0" java.lang.IllegalArgumentException: Cannot write value of type class java.lang.Double
	at clojure.tools.nrepl.bencode$eval46272$fn__46273.invoke(bencode.clj:326)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.tools.nrepl.bencode$eval46307$fn__46308.invoke(bencode.clj:398)
[...]
```

Full trace can be found here: https://gist.github.com/jcf/00e44de3eb97d43ca197

I've removed all but `cider-nrepl` from my `profiles.clj` and the problem persists. If I remove `cider-nrepl` too I can start a REPL just fine.

**Comment by Malabarba** [comment]
Could you provide a minimal project that causes this?

**Comment by Malabarba** [comment]
Just deployed a snapshot that should fix this. Let me know if it works (if it doesn't, we'll need an example).

**Comment by jcf** [comment]
Hi @Malabarba,

Thanks for shipping a fix. Unfortunately I'm still seeing the same exception with `[cider/cider-nrepl "0.10.0-20150910.083528-24"]`, which I'm assuming includes your fix based on the timestamp.

**Comment by Malabarba** [comment]
Ok, then could you provide a minimal example project? 
I haven't managed to reproduce the problem here yet.

**Comment by jcf** [comment]
It's a fairly large codebase so that'll take me a while. I'll see what I can do…

**Comment by Malabarba** [comment]
Thing that may help :

Do you set any kind of special Var metadata?
Where do you use floats in the codebase?

**Comment by Malabarba** [comment]
(I meant doubles, of course)

**Comment by jcf** [comment]
Hi @Malabarba,

Sorry for not getting back to you sooner. I was AFK all weekend.

I've been able to start up a REPL successfully this morning. I can only guess the snapshot I was using didn't contain your fix because I've not changed any code anywhere.

We do use a fair bit of [Schema][] in our codebase, which makes use of metadata in places. That's the only thing that springs to mind at least.

**All's well that ends well.** Thanks for helping with this issue, Artur.

[Schema]: https://github.com/Prismatic/schema

**Comment by drewr** [comment]
I'm still struggling with this issue. The problem doesn't happen on startup for me, but when running any request whose response contains a double, which is especially troublesome when running interactive tests. Judging from maven I'm running `cider-nrepl-0.10.0-20151004.164907-35`, and here's the prelude that prints out in my repl:

```
; CIDER 0.10.0snapshot (package: 20151011.151) (Java 1.8.0, Clojure 1.7.0, nREPL 0.2.10)
```

**Comment by Malabarba** [comment]
At least this doesn't seem to be about the track state middleware. 

When you say _"when running any request whose response contains a double"_, do you mean that the test's return value is a float?

**Comment by drewr** [comment]
That was a little ambiguous, I apologize. I mean during a test failure where there is an nrepl response telling me what happened. For example, if I do something like `(is (= :foo (+ 1 1)))`, which I often do just to see what `(+ 1 1)` looks like, it will hang because of the aforementioned exception in the server buffer.

**Comment by bbatsov** [comment]
The test given as an example doesn't produce a failure for me.

**Comment by drewr** [comment]
@bbatsov Maybe https://github.com/pjstadig/humane-test-output complicates the situation? Not sure why it would, but I have that in the mix.

**Comment by bbatsov** [comment]
Maybe. I've never used it, but I can imagine it can interfere with our `clojure.test` support if it monkey-patches something.

**Comment by jcf** [comment]
Removing humane-test-output fixes the issue for me.

**Comment by sickill** [comment]
Just stumbled upon this problem, and in my case it was also because of humane-test-output.
