### ISSUE TITLE
Returning an non-primitive object from a middleware locks up the middleware

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#332]
I'm not quite certain whether this is a cider or a cider-nrepl issue, but I'm reporting it here, so we won't forget about it.

## Expected behavior

Something like this should raise an error.

## Actual behavior

Everything locks up, no errors are raised.

## Steps to reproduce the problem

Edit the `eldoc-reply` method to return an ns object, instead of a string and try running eldoc in CIDER.

More info - https://github.com/clojure-emacs/cider-nrepl/pull/331#issuecomment-205024081 

### cider-nrepl version

0.12-snapshot

### Java version

1.8

### Operating system

OS X El Capitan

**Comment by sanjayl** [comment]
I used `tcpflow` to capture the communication across nREPL's port, and it looks like the cider-nrepl side is never generating a reply. (the command I used was `sudo tcpflow -i any -C -J port <nrepl-port-number>`).

I also used the java console to see if there are any hung threads on the server side, but it doesn't look like there are.

I'm guessing it's going to be on the tools.nrepl side of things? I could probably change the `with-safe-transport` macro to `pr` all the non-primitive values in the return map. I have a busy week at work this week so not sure if I'll be able to try it out, but I'll keep you updated if I do get a chance.

**Comment by bbatsov** [comment]
Thanks for looking into this @sanjayl!

**Comment by sanjayl** [comment]
Couple of quick questions:

1. Would you prefer that the non-bencodable items causing this type of error get automatically converted to something bencodable (likely a string), or would you prefer an error bubble up so that we're not silently transforming "out of bounds" data?
2. Do you know if tools.nrepl is actively being maintained and accepting patches, or should I just focus on putting a workaround in the cider-nrepl code first?

**Comment by bbatsov** [comment]
> Would you prefer that the non-bencodable items causing this type of error get automatically converted to something bencodable (likely a string), or would you prefer an error bubble up so that we're not silently transforming "out of bounds" data?

Let's raise an error.

> Do you know if tools.nrepl is actively being maintained and accepting patches, or should I just focus on putting a workaround in the cider-nrepl code first?

Yeah, it's still maintained by @cemerick. You'll have to submit the patch via nREPL's JIRA, though.

**Comment by bbatsov** [comment]
P.S. In general it's best to fix everything that can be fixed in nREPL in nREPL (as this benefits all nREPL users). Unfortunately it often takes a while to merge something there, so this is not always feasible in the short term.

**Comment by bbatsov** [comment]
Fixed by #333.

**Comment by sanjayl** [comment]
This unfortunately still doesn't work 100%. I had a big-time hang when trying to send a `sorted-map` of namespace symbols -> `sorted-set` of dependency symbols. Simplified the collections to lists and everything worked OK. Will keep on looking into this as I go along, just wanted to give you a heads up.

**Comment by bbatsov** [comment]
Good to know!
